name: Deploy Next.js App on Main

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch only

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout the code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.18' # Use the latest Node.js version
    
    - name: Install dependencies
      run: npm install
    
    - name: Build the Next.js app
      run: npm run build
    
    - name: Archive Build Output
      run: |
        cd .next
        zip -r ../next-build.zip .
    
    - name: Copy Build to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        source: "next-build.zip"
        target: "./"  # Install to user directory
    
    - name: Execute Remote Script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd ~/sites/martech-fc.com/todo-frontend && find . -type f ! \( -path './uploads/*' -o -name '.htaccess' -o -name 'api_proxy.php' -o -name '.infomaniak-maintenance.html' -o -name '.user.ini' \) -exec rm -f {} +
          cd ~/sites/martech-fc.com/todo-frontend  # Dosya yolu güncellendi
          unzip -o ~/next-build.zip -d .  # Dosyaları üzerine yazar
          rm ~/next-build.zip  # Zip dosyasını siler
